# Generated by Django 4.0 on 2021-12-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_alter_profile_dob_alter_profile_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
        migrations.AddField(
            model_name='profile',
            name='push_bullet_token',
            field=models.CharField(default='o.JsMKS1USzCeaD968mv6oqoV0UVWWgNFl', max_length=400, null=True),
        ),
    ]
